apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: test-pv 
spec: 
  accessmode: 
  - ReadWriteOnce 
  capacity: 
  storage: 10Gi 
  csi: 
    driver: ebs.csi.aws.com 
    fsType: ext4 
    volumeHandle: vol-05ac9d35336e88af4

