apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "ebs-sc" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic-pod
  labels: 
    purpose: "ebs-dynamic-demo"
spec:
  nodeSelector: 
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic


--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-dynamic
spec: 
  type: LoadBalancer
  selector: # labels are user as selectors 
    purpose: "ebs-dynamic-demo"
  ports:
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 30008