apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-nodeport
spec: 
  type: NodePort 
  selector: # labels are user as selectors 
    project: expense 
    component: backend 
    environement: dev 
    version: "1.0.0"
    demo: nodePort
  ports:
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 30007

--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: backend-nodeport
  labels: 
    project: expense 
    component: backend 
    environement: dev 
    version: "1.0.0"
    demp: nodePort
spec: 
  containers: 
  - name: nginx 
    image: nginx 