apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: nginx 
 # these labels are replicaset labels
  labels: 
    app: frontend 
    tier: web 
spec: 
  replicas: 2 
  selector: 
    matchLabels:
      app: frontend 
      tier: web 
  templates: 
    metadata: 
      labels: 
        app: frontend 
        tier: web 
    spec: 
      containers: 
      - name: nginx 
        image: nginx 
