apiVersion: v1
kind: Pod 
metadata: 
  name: myapp-pod
  labels: 
    app.kubernetes.io/name: MyApp
spec: 
  containers: 
  - name: nginx 
    image: nginx 
  initContainers: 
  - name: init-myservice 
    image: busybox:1.28 
    command: ['sh', '-c', "for i in {1..10}; do sleep 1; if nslookup myservice; then exit 0; fi; done; exit 1"]